IMAGE_NAME = "bento/debian-12"

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.define "debian" do |debian|
    debian.vm.box = IMAGE_NAME
    debian.vm.network "forwarded_port", guest: 22, host: 2206, host_ip: "127.0.0.1"
    debian.vm.hostname = "debian"

    debian.vm.provision "file", source: "id_rsa.pub", destination: "~/.ssh/me.pub"

    debian.vm.provision "shell", inline: <<-SHELL
      cat ~/.ssh/me.pub >> ~/.ssh/authorized_keys

      wget https://repo.zabbix.com/zabbix/7.4/debian/pool/main/z/zabbix-release/zabbix-release_latest_7.4+debian12_all.deb -O /tmp/zabbix.deb
      dpkg -i /tmp/zabbix.deb
      apt update && apt install -y zabbix-agent2

      cat > /etc/zabbix/zabbix_agent2.conf <<EOF
Server=127.0.0.1
Hostname=debian
EOF

      mkdir -p /var/log/zabbix && chown zabbix: /var/log/zabbix
      systemctl enable --now zabbix-agent2
    SHELL
  end
end